# Generated by Django 4.0.6 on 2022-07-17 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('summary', models.CharField(max_length=250)),
                ('detail', models.TextField(blank=True, max_length=500)),
                ('deadlineTime', models.TimeField()),
                ('deadlineDate', models.DateField()),
                ('priority', models.CharField(choices=[('Low', 'low'), ('Normal', 'normal'), ('High', 'high'), ('Doing', 'doing'), ('Done', 'done')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userName', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('displayName', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doing', models.ForeignKey(blank=True, limit_choices_to={'priority': 'doing'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='TaskPriority_BE.task')),
                ('done', models.ForeignKey(blank=True, limit_choices_to={'priority': 'done'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='TaskPriority_BE.task')),
                ('high', models.ForeignKey(blank=True, limit_choices_to={'priority': 'high'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='TaskPriority_BE.task')),
                ('low', models.ForeignKey(blank=True, limit_choices_to={'priority': 'low'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='TaskPriority_BE.task')),
                ('normal', models.ForeignKey(blank=True, limit_choices_to={'priority': 'normal'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='TaskPriority_BE.task')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TaskPriority_BE.users')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TaskPriority_BE.users'),
        ),
    ]
