# Generated by Django 4.0.6 on 2022-07-18 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskPriority_BE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadlineDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='deadlineTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='detail',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
