# Generated by Django 4.0.6 on 2022-07-18 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskPriority_BE', '0002_task_deadlinedate_task_deadlinetime_task_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TaskPriority_BE.users'),
        ),
    ]
