# Generated by Django 4.0.6 on 2022-07-30 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskPriority_BE', '0004_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(default='huyenpham', on_delete=django.db.models.deletion.CASCADE, to='TaskPriority_BE.users'),
            preserve_default=False,
        ),
    ]
